### ISSUE TITLE
AttributeError: type object 'Column' has no attribute 'update'

### ISSUE THREAD

**Issue by broken** [alexandersokol/sd-model-organizer#102]
The stacktrace:

```
AttributeError: type object 'Column' has no attribute 'update'
Traceback (most recent call last):
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "C:\pinokio\api\stable-diffusion-webui-forge.git\app\extensions\sd-model-organizer\scripts\mo\ui_main.py", line 24, in on_json_box_change
    gr.Column.update(visible=is_home_visible),
```

I believe it is because of: https://github.com/gradio-app/gradio/issues/6862

I have gradio==4.40.0

I am unable to downgrade gradio, because I am using this in Forge which requires gradio-rangeslider, and all of its versions require gradio > 4.

**Comment by Learwin** [comment]
I may be out of the loop but what is Forge ?

**Comment by broken** [comment]
It's basically a new version of the Stable Diffusion WebUI built on top of the most recent version of gradio with some other optimisations.

https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by Bortus-AI** [comment]
confirmed not working with forge and gradio==4.40.0

**Comment by harukaxxxx** [comment]
Since the original developer is no longer active, I am maintaining this extension for my own purposes.
If you are interested in it, the issue has been fixed in my repository:
https://github.com/harukaxxxx/sd-model-organizer
Please back up your database (SQLite file) before using.
