### ISSUE TITLE
Error loading script: model_organizer.py on SD webui v1.2.1

### ISSUE THREAD

**Issue by pek77** [alexandersokol/sd-model-organizer#22]
![图片](https://github.com/alexandersokol/sd-model-organizer/assets/12756666/b5d23902-4078-4458-8a2a-e9d6b7b0664b)

Error loading script: model_organizer.py
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/ubuntu/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-model-organizer/scripts/model_organizer.py", line 7, in <module>
    from scripts.mo.data.init_storage import initialize_storage
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-model-organizer/scripts/mo/data/init_storage.py", line 1, in <module>
    from scripts.mo.environment import env, STORAGE_SQLITE, STORAGE_FIREBASE
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-model-organizer/scripts/mo/environment.py", line 7, in <module>
    from scripts.mo.data.storage import Storage
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-model-organizer/scripts/mo/data/storage.py", line 49, in <module>
    class Storage(ABC):
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd-model-organizer/scripts/mo/data/storage.py", line 52, in Storage
    def get_all_records(self) -> list[Record]:
TypeError: 'type' object is not subscriptable

**Comment by alexandersokol** [comment]
what python version are you using?

**Comment by pek77** [comment]
Python 3.8.10

**Comment by Gyztor** [comment]
Same issue here with Stable Diffusion webui v1.3.0 with python 3.8.5

**Comment by alexandersokol** [comment]
I was kinda sure that webui requires 3.10, at least it is said in the README in windows install section.
Anyway, I pushed changes that should fix this issue for python 3.9 and older, can you try it? 
Keep in mind this branch is unstable.

**Comment by alexandersokol** [comment]
Fixed.
