### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by harukaxxxx** [alexandersokol/sd-model-organizer#30]
I have error that extension don't show any records after update to v1.1, I have custom path for models and lort etc.

![image](https://github.com/alexandersokol/sd-model-organizer/assets/5777085/3f68f7da-20cc-48c8-a941-bb5b7adf5874)
![image](https://github.com/alexandersokol/sd-model-organizer/assets/5777085/8cbdda0d-f2f4-4b9e-92b5-0b46433144a3)

version: v1.3.2
python: 3.10.10
torch: 2.0.1+cu118
xformers: N/A
gradio: 3.32.0

```
Traceback (most recent call last):
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\ui_home.py", line 14, in _prepare_data
    records = load_records_and_filter(state, True)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\data\record_utils.py", line 159, in load_records_and_filter
    local_records = _create_record_from_files(not_bound_files)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\data\record_utils.py", line 121, in _create_record_from_files
    rec = _create_record_from_file(file)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\data\record_utils.py", line 115, in _create_record_from_file
    return _create_model_from_info_file(model_file_path, info_file, model_type)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\data\record_utils.py", line 62, in _create_model_from_info_file
    version_dict = create_version_dict(json_data)
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\data\mapping_utils.py", line 6, in create_version_dict
    'id': version_data['id'],
KeyError: 'id'
```

**Comment by harukaxxxx** [comment]
Wow! You're super efficient! The problem has been resolved. Thank you very much!
