### ISSUE TITLE
Decoding error blocks MO library from loading

### ISSUE THREAD

**Issue by joelyoder** [alexandersokol/sd-model-organizer#57]
Automatic version: [SD.Next](https://github.com/vladmandic/automatic) (latest version)
Python version: 3.10.6

I've been hitting this error whenever I attempt to load my library in MO:
`Traceback (most recent call last):
  File "E:\AI\generators\automatic\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\generators\automatic\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\AI\generators\automatic\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\generators\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\generators\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AI\generators\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI\generators\automatic\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\generators\automatic\extensions\sd-model-organizer\scripts\mo\ui_home.py", line 12, in _prepare_data
    state = json.loads(state_json)
  File "C:\Users\joely\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\joely\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\joely\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I was concerned that my DB got corrupted, so I copied out the SQL lite file in the plugin directory and rebooted SD and let it create a fresh DB and I still hit this issue.

Any ideas of what I could try next to pinpoint the issue? I don't know Python so Googling the error wasn't very helpful. :/

**Comment by alexandersokol** [comment]
Hello!
I'm not sure but it is kinda hard to currupt data that is in SQLite db, it should contain only data for displaying. 

The error you posted above says that currepted state data came to the json. This state simpy stores screen state, for home screen it contains data like filtering options, search query etc. 

I tried to SD.next (never used it before) and found out that js script wasn't loading due to already defined method. But I see that there are might be some other errors, like dark theme not loading. Looks like SD.next has some things that work differently like in origin Automatic WEBUI.

Try to update externsion to the latest version, I hope it will solve your issue.

**Comment by joelyoder** [comment]
Backing up my database, deleting the plugin, cloning it down fresh from Git, and then dropping my database back in has fixed it.

Still not sure what was causing this issue, but thankfully it's working again.
